name: ADLC3
on:
  push:
    branches:
      - main
      - "^release/v[0-9]+.[0-9]+$"

jobs:
  CICD_MyCA:
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "CICD_Daniel"
			- name: Send my Info
				id: slack
				uses: slackapi/slack-github-action@v1.23.0
				with:
					payload: |
						{

						}
				env:
					SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK