name: ADLC3
on:
  push:
    branches:
      - main
      - "^release/v[0-9]+.[0-9]+$"

jobs:
  CICD_MyCA:
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest
    steps:
		
      - name: Checkout source
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "CICD_Daniel"

      - name: Send my information
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*DipSA 56 CICD Submission*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:* Xu Ziyi"                                  
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email:* E1112891@u.nus.edu"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Matriculation:* A0269508R"              
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:* ${{ github.server_url }}/${{ github.repository }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ secrets.RAILWAY_URL }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Go",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "${{ secrets.RAILWAY_URL }}",
                    "action_id": "button-action"
                  }
                }
              ]
            }
       env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

